---
name: Daily Profile Update

on:
  schedule:
    # Run every hour for testing
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-profile:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up dependencies
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y emacs-nox jq make

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # GitHub CLI is pre-installed on GitHub-hosted runners

      - name: Run make all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ubuntu runners use 'make' not 'gmake'
          make all
          make test-display || { echo "Display format check failed!"; exit 1; }
